version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Ho_Chi_Minh"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Ho_Chi_Minh"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
      - "dependencies"
